In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

In [3]:
list_of_orders = pd.read_csv(r"./Dataset/List_of_Orders.csv")

In [4]:
Order_Details = pd.read_csv(r"./Dataset/Order_Details.csv")
Sales_Target = pd.read_csv(r"./Dataset/Sales_Target.csv")

In [7]:
list_of_orders.head()

  Order_ID  Order_Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [8]:
Order_Details.head()

  Order_ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601    1275   -1148         7    Furniture         Bookcases
1  B-25601      66     -12         5     Clothing             Stole
2  B-25601       8      -2         3     Clothing       Hankerchief
3  B-25601      80     -56         4  Electronics  Electronic Games
4  B-25602     168    -111         2  Electronics            Phones

In [9]:
Sales_Target.head()

  Month_of_Order_Date   Category  Target
0              Apr-18  Furniture   10400
1              May-18  Furniture   10500
2              Jun-18  Furniture   10600
3              Jul-18  Furniture   10800
4              Aug-18  Furniture   10900

In [5]:
import sqlite3

conn = sqlite3.connect('E_Commerce.db')

In [ ]:
list_of_orders.to_sql('List_of_Orders', conn, index=False)
Order_Details.to_sql('Order_Details', conn, index=False)
Sales_Target.to_sql('Sales_Target', conn, index=False)

In [13]:
query = "SELECT * FROM List_of_Orders"
result = pd.read_sql_query(query, conn)
print(result.head())

  Order_ID  Order_Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [15]:
# conn.close()

# import os

# os.remove("E-Commerce.db")

In [16]:
conn = sqlite3.connect('E_Commerce.db')

In [11]:
query = "CREATE VIEW Total_Sales AS SELECT SUM(amount) AS Total_Sales FROM Order_Details"
conn.execute(query)

result = pd.read_sql_query("SELECT * FROM Total_Sales", conn)
print(result)

   Total_Sales
0       431502

In [18]:
result.to_csv("Total_Sales.csv", index=False)

In [15]:
query = "create view Total_Profit as select sum(profit) as Total_Profit from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Profit", conn)

In [16]:
print(result)

   Total_Profit
0         23955

In [19]:
query = "create view Unique_Orders as select count(distinct(order_id)) as Unique_Orders from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Unique_Orders", conn)
print(result)

   Unique_Orders
0            500

In [20]:
query = "create view Total_Orders as select count(order_id) as Total_Orders from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Orders", conn)
print(result)

   Total_Orders
0          1500

In [21]:
query = "create view Unique_Customers as select count(distinct(CustomerName)) as Unique_Customers from List_of_Orders"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Unique_Customers", conn)
print(result)

   Unique_Customers
0               332

In [22]:
query = "create view Total_Customers as select count(CustomerName) as Total_Customers from List_of_Orders"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Customers", conn)
print(result)

   Total_Customers
0              500

In [23]:
query = "create view Total_Quantity_Sold as select sum(quantity) as Total_Quantity_Sold from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Quantity_Sold", conn)
print(result)

   Total_Quantity_Sold
0                 5615

In [24]:
query = "create view Average_Order_Value as select sum(amount)/count(order_id) as Average_Order_Value from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Average_Order_Value", conn)
print(result)

   Average_Order_Value
0                  287

In [25]:
query = "create view Average_Order_Profit as select sum(profit)/count(order_id) as Average_Order_Profit from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Average_Order_Profit", conn)
print(result)

   Average_Order_Profit
0                    15

In [26]:
query = "create view Profit_Margin as select (sum(profit) * 100 / sum(amount))  as Profit_Margin from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Profit_Margin", conn)
print(result)

   Profit_Margin
0              5

In [27]:
query = "create view Average_Order_per_Quantity as select sum(quantity)/count(distinct(order_id)) as Average_Order_per_Quantity from Order_Details"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Average_Order_per_Quantity", conn)
print(result)

   Average_Order_per_Quantity
0                          11

In [28]:
query = "create view Total_Sales_by_Category_Subcategory as select category, \"sub-category\", sum(amount) as Total_Sales from Order_Details group by 1, 2 order by 3 desc"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Sales_by_Category_Subcategory", conn)
print(result)

       Category      Sub-Category  Total_Sales
0   Electronics          Printers        58252
1     Furniture         Bookcases        56861
2      Clothing             Saree        53511
3   Electronics            Phones        46119
4   Electronics  Electronic Games        39168
5     Furniture            Chairs        34222
6      Clothing          Trousers        30039
7     Furniture            Tables        22614
8   Electronics       Accessories        21728
9      Clothing             Stole        18546
10     Clothing       Hankerchief        14608
11    Furniture       Furnishings        13484
12     Clothing             Shirt         7555
13     Clothing           T-shirt         7382
14     Clothing             Kurti         3361
15     Clothing          Leggings         2106
16     Clothing             Skirt         1946

In [7]:
conn.execute("DROP VIEW IF EXISTS Total_Sales_by_Category")

query = """
CREATE VIEW Total_Sales_by_Category AS
SELECT category, SUM(amount) AS Total_Sales
FROM Order_Details
GROUP BY category
ORDER BY Total_Sales DESC
"""
conn.execute(query)

result = pd.read_sql_query("SELECT * FROM Total_Sales_by_Category", conn)
print(result)

      Category  Total_Sales
0  Electronics       165267
1     Clothing       139054
2    Furniture       127181

In [48]:
query = "create view Total_Profit_by_Cat_SubCat as select Category, \"sub-category\" as Sub_Category, sum(profit) as Total_Profit from Order_Details group by 1, 2 order by 3 desc"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Profit_by_Cat_SubCat", conn)
print(result)

       Category      Sub_Category  Total_Profit
0   Electronics          Printers          5964
1     Furniture         Bookcases          4888
2   Electronics       Accessories          3559
3      Clothing          Trousers          2847
4      Clothing             Stole          2559
5   Electronics            Phones          2207
6      Clothing       Hankerchief          2098
7      Clothing           T-shirt          1500
8      Clothing             Shirt          1131
9     Furniture       Furnishings           844
10    Furniture            Chairs           577
11     Clothing             Saree           352
12     Clothing          Leggings           260
13     Clothing             Skirt           235
14     Clothing             Kurti           181
15  Electronics  Electronic Games         -1236
16    Furniture            Tables         -4011

In [49]:
query = """
create view Total_Sales_by_State_City as
select l.State, l.City, sum(o.amount) as Total_Sales
from List_of_Orders l join Order_Details o on l.order_id = o.order_id
group by 1, 2 order by 3 desc
"""
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Sales_by_State_City", conn)
print(result)

                State                City  Total_Sales
0      Madhya Pradesh              Indore        79069
1         Maharashtra              Mumbai        61867
2         Maharashtra                Pune        33481
3      Madhya Pradesh              Bhopal        23583
4               Delhi               Delhi        22531
5       Uttar Pradesh           Allahabad        16857
6           Karnataka           Bangalore        15058
7             Gujarat           Ahmedabad        14230
8         West Bengal             Kolkata        14086
9             Kerala   Thiruvananthapuram        13459
10     Andhra Pradesh           Hyderabad        13256
11              Bihar               Patna        12943
12             Punjab          Chandigarh        12279
13           Nagaland              Kohima        11903
14          Rajasthan             Udaipur        11073
15  Jammu and Kashmir             Kashmir        10829
16          Rajasthan              Jaipur        10076
17            Haryana          Chandigarh         8863
18   Himachal Pradesh               Simla         8666
19            Gujarat               Surat         6828
20                Goa                 Goa         6705
21         Tamil Nadu             Chennai         6087
22      Uttar Pradesh             Lucknow         5502
23             Sikkim             Gangtok         5276
24             Punjab            Amritsar         4507
25     Madhya Pradesh               Delhi         2488

In [50]:
query = """
create view Total_Profit_by_State_City as
select l.State, l.City, sum(o.profit) as Total_Profit
from List_of_Orders l join Order_Details o on l.order_id = o.order_id
group by 1, 2 order by 3 desc
"""
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Total_Profit_by_State_City", conn)
print(result)

                State                City  Total_Profit
0         Maharashtra                Pune          4539
1      Madhya Pradesh              Indore          4159
2       Uttar Pradesh           Allahabad          3081
3               Delhi               Delhi          2987
4         West Bengal             Kolkata          2500
5           Rajasthan             Udaipur          2010
6             Kerala   Thiruvananthapuram          1871
7         Maharashtra              Mumbai          1637
8             Gujarat               Surat          1345
9             Haryana          Chandigarh          1325
10     Madhya Pradesh              Bhopal           871
11   Himachal Pradesh               Simla           656
12          Karnataka           Bangalore           645
13             Punjab            Amritsar           544
14     Madhya Pradesh               Delhi           521
15             Sikkim             Gangtok           401
16                Goa                 Goa           370
17      Uttar Pradesh             Lucknow           156
18           Nagaland              Kohima           148
19  Jammu and Kashmir             Kashmir             8
20              Bihar               Patna          -321
21     Andhra Pradesh           Hyderabad          -496
22          Rajasthan              Jaipur          -753
23            Gujarat           Ahmedabad          -880
24             Punjab          Chandigarh         -1153
25         Tamil Nadu             Chennai         -2216

In [8]:
conn.execute("DROP VIEW IF EXISTS Monthly_Sales")
query = """
CREATE VIEW Monthly_Sales AS
SELECT
    date(
        substr(l.Order_Date, 7, 4) || '-' ||
        substr(l.Order_Date, 4, 2) || '-' ||
        '01'
    ) AS Month,

    SUM(o.Amount) AS Total_Sales

FROM List_of_Orders AS l
JOIN Order_Details AS o
ON l.Order_ID = o.Order_ID

GROUP BY Month
ORDER BY Month;
"""
conn.execute(query)
print(pd.read_sql_query("SELECT * FROM Monthly_Sales", conn))

         Month  Total_Sales
0   2018-04-01        32726
1   2018-05-01        28545
2   2018-06-01        23658
3   2018-07-01        12966
4   2018-08-01        30899
5   2018-09-01        26628
6   2018-10-01        31615
7   2018-11-01        48086
8   2018-12-01        37579
9   2019-01-01        61439
10  2019-02-01        38424
11  2019-03-01        58937

In [ ]:
conn.execute("DROP VIEW IF EXISTS Quarterly_Sales")
query = """
CREATE VIEW Quarterly_Sales AS
SELECT
    substr(l.Order_Date, 7, 4) || '-Q' ||
    CASE
        WHEN CAST(substr(l.Order_Date, 4, 2) AS INTEGER) BETWEEN 1 AND 3 THEN '1'
        WHEN CAST(substr(l.Order_Date, 4, 2) AS INTEGER) BETWEEN 4 AND 6 THEN '2'
        WHEN CAST(substr(l.Order_Date, 4, 2) AS INTEGER) BETWEEN 7 AND 9 THEN '3'
        ELSE '4'
    END AS Quarter,

    SUM(o.Amount) AS Total_Sales

FROM List_of_Orders AS l
JOIN Order_Details AS o
    ON l.Order_ID = o.Order_ID

GROUP BY Quarter
ORDER BY Quarter
"""
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Quarterly_Sales", conn)
print(result)

   Quarter  Total_Sales
0  2018-Q2        84929
1  2018-Q3        70493
2  2018-Q4       117280
3  2019-Q1       158800

In [7]:
query = "create view Profit_Margin_by_Category_SubCategory as select Category, \"sub-category\" as Sub_Category, (sum(profit) * 100 / sum(amount)) as Profit_Margin_pct from Order_Details group by 1, 2"
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Profit_Margin_by_Category_SubCategory", conn)
print(result)

       Category      Sub_Category  Profit_Margin_pct
0      Clothing       Hankerchief                 14
1      Clothing             Kurti                  5
2      Clothing          Leggings                 12
3      Clothing             Saree                  0
4      Clothing             Shirt                 14
5      Clothing             Skirt                 12
6      Clothing             Stole                 13
7      Clothing           T-shirt                 20
8      Clothing          Trousers                  9
9   Electronics       Accessories                 16
10  Electronics  Electronic Games                 -3
11  Electronics            Phones                  4
12  Electronics          Printers                 10
13    Furniture         Bookcases                  8
14    Furniture            Chairs                  1
15    Furniture       Furnishings                  6
16    Furniture            Tables                -17

In [10]:
conn.execute("DROP VIEW IF EXISTS Profit_Margin_by_State_City")
query = """
create view Profit_Margin_by_State_City as
select l.State as State, l.City as City, sum(od.profit) * 100 / sum(od.amount) as Profit_Margin_pct
from List_of_Orders l join Order_Details od on l.order_id = od.order_id
group by 1, 2 order by 3 desc
"""
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Profit_Margin_by_State_City", conn)
print(result)

                State                City  Profit_Margin_pct
0      Madhya Pradesh               Delhi                 20
1             Gujarat               Surat                 19
2           Rajasthan             Udaipur                 18
3       Uttar Pradesh           Allahabad                 18
4         West Bengal             Kolkata                 17
5             Haryana          Chandigarh                 14
6               Delhi               Delhi                 13
7             Kerala   Thiruvananthapuram                 13
8         Maharashtra                Pune                 13
9              Punjab            Amritsar                 12
10   Himachal Pradesh               Simla                  7
11             Sikkim             Gangtok                  7
12                Goa                 Goa                  5
13     Madhya Pradesh              Indore                  5
14          Karnataka           Bangalore                  4
15     Madhya Pradesh              Bhopal                  3
16        Maharashtra              Mumbai                  2
17      Uttar Pradesh             Lucknow                  2
18           Nagaland              Kohima                  1
19  Jammu and Kashmir             Kashmir                  0
20              Bihar               Patna                 -2
21     Andhra Pradesh           Hyderabad                 -3
22            Gujarat           Ahmedabad                 -6
23          Rajasthan              Jaipur                 -7
24             Punjab          Chandigarh                 -9
25         Tamil Nadu             Chennai                -36

In [16]:
conn.execute("DROP VIEW IF EXISTS Profit_contribution_by_Category_SubCategory")
query = """
CREATE VIEW Profit_contribution_by_Category_SubCategory AS
SELECT 
    Category,
    \"sub-category\" as Sub_Category,
    (SUM(profit) * 100.0 / (SELECT SUM(profit) FROM Order_Details)) AS Profit_Contribution_pct
FROM Order_Details
GROUP BY Category, Sub_Category
ORDER BY Category, Sub_Category;
"""
conn.execute(query)
result = pd.read_sql_query("SELECT * FROM Profit_contribution_by_Category_SubCategory", conn)
print(result)

       Category      Sub_Category  Profit_Contribution_pct
0      Clothing       Hankerchief                 8.758088
1      Clothing             Kurti                 0.755583
2      Clothing          Leggings                 1.085368
3      Clothing             Saree                 1.469422
4      Clothing             Shirt                 4.721353
5      Clothing             Skirt                 0.981006
6      Clothing             Stole                10.682530
7      Clothing           T-shirt                 6.261741
8      Clothing          Trousers                11.884784
9   Electronics       Accessories                14.857024
10  Electronics  Electronic Games                -5.159674
11  Electronics            Phones                 9.213108
12  Electronics          Printers                24.896681
13    Furniture         Bookcases                20.404926
14    Furniture            Chairs                 2.408683
15    Furniture       Furnishings                 3.523273
16    Furniture            Tables               -16.743895

In [17]:
result = pd.read_sql_query("select category, sum(Profit_Contribution_pct) as Total_Profit_Contribution from Profit_contribution_by_Category_SubCategory group by 1 order by 2 desc", conn)
print(result)

      Category  Total_Profit_Contribution
0     Clothing                  46.599875
1  Electronics                  43.807138
2    Furniture                   9.592987

In [18]:
result = pd.read_sql_query("SELECT sum(Profit_Contribution_pct) as Total_Profit_Contribution FROM Profit_contribution_by_Category_SubCategory", conn)
print(result)

   Total_Profit_Contribution
0                      100.0

In [25]:
query ="""
create view top_10_cust_by_sales_profit as
select l.CustomerName, sum(o.Amount) as Total_Sales, sum(o.Profit) as Total_Profit
from List_of_Orders l join Order_Details o on l.order_id = o.order_id
group by 1
order by 2 desc limit 10
"""
conn.execute(query)
print(pd.read_sql_query("SELECT * FROM top_10_cust_by_sales_profit", conn))

  CustomerName  Total_Sales  Total_Profit
0       Yaanvi         9177           488
1        Pooja         9030          -269
2     Abhishek         8135          1314
3      Surabhi         6889           412
4       Soumya         6869           894
5      Harshal         6026           864
6     Priyanka         5762          1340
7       Shruti         5750           485
8     Abhijeet         5691          1562
9       Sarita         5449          1265

In [41]:
conn.execute("DROP VIEW IF EXISTS monthly_actual_sales")
query = """
CREATE VIEW monthly_actual_sales AS
SELECT
    (CASE CAST(substr(l.Order_Date,4,2) AS INTEGER)
        WHEN 1 THEN 'Jan' WHEN 2 THEN 'Feb' WHEN 3 THEN 'Mar' WHEN 4 THEN 'Apr'
        WHEN 5 THEN 'May' WHEN 6 THEN 'Jun' WHEN 7 THEN 'Jul' WHEN 8 THEN 'Aug'
        WHEN 9 THEN 'Sep' WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dec' END)
    || '-' || substr(l.Order_Date,9,2) AS Month_of_Order_Date,
    od.Category,
    SUM(od.Amount) AS Actual_Sales
FROM List_of_Orders l
JOIN Order_Details od ON l.Order_ID = od.Order_ID
GROUP BY 1, 2
"""
conn.execute(query)
print(pd.read_sql_query("SELECT * FROM monthly_actual_sales", conn))

   Month_of_Order_Date     Category  Actual_Sales
0               Apr-18     Clothing         13478
1               Apr-18  Electronics         11127
2               Apr-18    Furniture          8121
3               Aug-18     Clothing         11822
4               Aug-18  Electronics          9539
5               Aug-18    Furniture          9538
6               Dec-18     Clothing          9545
7               Dec-18  Electronics         18560
8               Dec-18    Furniture          9474
9               Feb-19     Clothing          9569
10              Feb-19  Electronics         12593
11              Feb-19    Furniture         16262
12              Jan-19     Clothing         13466
13              Jan-19  Electronics         26716
14              Jan-19    Furniture         21257
15              Jul-18     Clothing          2981
16              Jul-18  Electronics          6502
17              Jul-18    Furniture          3483
18              Jun-18     Clothing          8782
19              Jun-18  Electronics          9344
20              Jun-18    Furniture          5532
21              Mar-19     Clothing         21418
22              Mar-19  Electronics         20860
23              Mar-19    Furniture         16659
24              May-18     Clothing          9518
25              May-18  Electronics         12807
26              May-18    Furniture          6220
27              Nov-18     Clothing         16270
28              Nov-18  Electronics         16651
29              Nov-18    Furniture         15165
30              Oct-18     Clothing         11488
31              Oct-18  Electronics         13361
32              Oct-18    Furniture          6766
33              Sep-18     Clothing         10717
34              Sep-18  Electronics          7207
35              Sep-18    Furniture          8704

In [42]:
conn.execute("DROP VIEW IF EXISTS category_sales_target_vs_actual_monthly")
query2 = """
CREATE VIEW category_sales_target_vs_actual_monthly AS
SELECT
    st.Month_of_Order_Date,
    st.Category,
    st.Target AS Target_Sales,
    COALESCE(ma.Actual_Sales, 0) AS Actual_Sales,
    COALESCE(ma.Actual_Sales, 0) - st.Target AS Variance,
    ROUND(COALESCE(ma.Actual_Sales, 0) * 100.0 / st.Target, 1) AS Target_Achieved_Pct
FROM Sales_Target st
LEFT JOIN monthly_actual_sales ma
    ON st.Category = ma.Category
    AND st.Month_of_Order_Date = ma.Month_of_Order_Date
ORDER BY st.Category, st.Month_of_Order_Date
"""
conn.execute(query2)
result = pd.read_sql_query("SELECT * FROM category_sales_target_vs_actual_monthly", conn)
print(result)

   Month_of_Order_Date     Category  Target_Sales  Actual_Sales  Variance  \
0               Apr-18     Clothing         12000         13478      1478
1               Aug-18     Clothing         14000         11822     -2178
2               Dec-18     Clothing         16000          9545     -6455
3               Feb-19     Clothing         16000          9569     -6431
4               Jan-19     Clothing         16000         13466     -2534
5               Jul-18     Clothing         14000          2981    -11019
6               Jun-18     Clothing         12000          8782     -3218
7               Mar-19     Clothing         16000         21418      5418
8               May-18     Clothing         12000          9518     -2482
9               Nov-18     Clothing         16000         16270       270
10              Oct-18     Clothing         16000         11488     -4512
11              Sep-18     Clothing         14000         10717     -3283
12              Apr-18  Electronics          9000         11127      2127
13              Aug-18  Electronics          9000          9539       539
14              Dec-18  Electronics          9000         18560      9560
15              Feb-19  Electronics         16000         12593     -3407
16              Jan-19  Electronics         16000         26716     10716
17              Jul-18  Electronics          9000          6502     -2498
18              Jun-18  Electronics          9000          9344       344
19              Mar-19  Electronics         16000         20860      4860
20              May-18  Electronics          9000         12807      3807
21              Nov-18  Electronics          9000         16651      7651
22              Oct-18  Electronics          9000         13361      4361
23              Sep-18  Electronics          9000          7207     -1793
24              Apr-18    Furniture         10400          8121     -2279
25              Aug-18    Furniture         10900          9538     -1362
26              Dec-18    Furniture         11400          9474     -1926
27              Feb-19    Furniture         11600         16262      4662
28              Jan-19    Furniture         11500         21257      9757
29              Jul-18    Furniture         10800          3483     -7317
30              Jun-18    Furniture         10600          5532     -5068
31              Mar-19    Furniture         11800         16659      4859
32              May-18    Furniture         10500          6220     -4280
33              Nov-18    Furniture         11300         15165      3865
34              Oct-18    Furniture         11100          6766     -4334
35              Sep-18    Furniture         11000          8704     -2296

    Target_Achieved_Pct
0                 112.3
1                  84.4
2                  59.7
3                  59.8
4                  84.2
5                  21.3
6                  73.2
7                 133.9
8                  79.3
9                 101.7
10                 71.8
11                 76.5
12                123.6
13                106.0
14                206.2
15                 78.7
16                167.0
17                 72.2
18                103.8
19                130.4
20                142.3
21                185.0
22                148.5
23                 80.1
24                 78.1
25                 87.5
26                 83.1
27                140.2
28                184.8
29                 32.3
30                 52.2
31                141.2
32                 59.2
33                134.2
34                 61.0
35                 79.1

In [46]:
conn.execute("DROP VIEW IF EXISTS monthly_sales_target_vs_actual")

query = """
CREATE VIEW monthly_sales_target_vs_actual AS
SELECT
    Month_of_Order_Date,
    SUM(Target_Sales) AS Target_Sales,
    SUM(Actual_Sales) AS Actual_Sales,
    SUM(Variance) AS Variance,
    ROUND(SUM(Actual_Sales) * 100.0 / SUM(Target_Sales), 1) AS Target_Achieved_Pct
FROM category_sales_target_vs_actual_monthly
GROUP BY Month_of_Order_Date
ORDER BY Month_of_Order_Date
"""

conn.execute(query)
print(pd.read_sql_query("SELECT * FROM monthly_sales_target_vs_actual", conn))

   Month_of_Order_Date  Target_Sales  Actual_Sales  Variance  \
0               Apr-18         31400         32726      1326
1               Aug-18         33900         30899     -3001
2               Dec-18         36400         37579      1179
3               Feb-19         43600         38424     -5176
4               Jan-19         43500         61439     17939
5               Jul-18         33800         12966    -20834
6               Jun-18         31600         23658     -7942
7               Mar-19         43800         58937     15137
8               May-18         31500         28545     -2955
9               Nov-18         36300         48086     11786
10              Oct-18         36100         31615     -4485
11              Sep-18         34000         26628     -7372

    Target_Achieved_Pct
0                 104.2
1                  91.1
2                 103.2
3                  88.1
4                 141.2
5                  38.4
6                  74.9
7                 134.6
8                  90.6
9                 132.5
10                 87.6
11                 78.3